name = "Codex UM Rock Avocado Trace"
description = "Server-side diagnostic logging for rock avocado bush growable/pickable state. Does not modify gameplay logic."
author = "Codex"
version = "1.0.0"
forumthread = ""
api_version = 10
dst_compatible = true
all_clients_require_mod = false
client_only_mod = false
server_only_mod = true
icon_atlas = ""
icon = ""
configuration_options = {}
